### ISSUE TITLE
Catalogue SourcePackageURL with localhost/127.0.0.1

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#23]
Hi,

I just can put the Catalogue working with our (ptinovacao) catalogue-database (catalogue-objects), but a doubt appears.

The sourcePackageURL, have an url with localhost.

```json
{
  "objectName": "HypertyChat",
  "description": "This is an example hyperty that is written in an external file and contains a source package",
  "sourcePackageURL": "https://127.0.0.1/.well-known/sourcepackage/984919876451321",
  "language": "Javascript ECMA6",
  "dataObjects": "[]"
}
```
I think, I did all right.

You can test on our testbed: https://catalogue.hybroker.rethink.ptinovacao.pt/client/

I don't know if this issue is related with #20

**Comment by emmelmann-fokus** [comment]
Yes,

this is correct.  This is the default behavior in case someone want to set up all components on localhost.

You'll need to start the database with the -d option to set the hostname / ip used in the sourcePackageURL.

so do something like:

$ docker run  catalogue-database -d catalogue.rethink.pt



I just noticed that I missed to explain this in D6.1, apologies.  I will update the doc.

**Comment by vitormsilva** [comment]
Hi,

i try to do what you said, but without success.

With docker-compse we can easily start all docker, but when i try to up with the options you have i always have the same problem.

can you look into my docker-compose.yml

```yaml
version: '2'
services: 
  'catalogue-database':
    image: rethink/catalogue-database
    container_name: 'catalogue-database'
    network_mode: "service:catalogue-broker"
    depends_on:
      - 'catalogue-broker'
  'catalogue-broker':
    image: rethink/catalogue-broker
    container_name: 'catalogue-broker'
    networks:
      - mynet123
    ports: 
      - '443:5683'
    hostname: 'catalogue.hybroker.rethink.ptinovacao.pt'
    expose:
      - '443'
      - '5683'

networks:
  mynet123:
    driver: bridge
```
This works, i can get the this result:
```json
{
  "cguid": "984919876451321",
  "hypertyType": "COMMUNICATOR",
  "version": "1.0",
  "objectName": "FirstHyperty",
  "description": "This is an example hyperty that is written in an external file and contains a source package",
  "sourcePackageURL": "https://localhost/.well-known/sourcepackage/984919876451321",
  "language": "Javascript ECMA6",
  "dataObjects": "[]"
}
```
but sourcePackageURL: always have localhost

Can you help me?
